### ISSUE TITLE
could not be loaded 

### ISSUE THREAD

**Issue by jumping** [gocd-contrib/gitlab-oauth-authorization-plugin#1]
I uploaded the gitlab-oauth-login-2.4.jar into /var/lib/go-server/plugins/external/, and also restart the go-server. But the gitlab did not display under the "Authorization Configurations".
![image](https://user-images.githubusercontent.com/255390/40355372-c684e8a0-5de8-11e8-8525-d8e116438c2d.png)

**Comment by ketan** [comment]
`gitlab-oauth-login-2.4.jar` seems to indicate that you're using the old plugin from https://github.com/gocd-contrib/gocd-oauth-login/releases. Please download a new plugin from https://github.com/gocd-contrib/gitlab-oauth-authorization-plugin/releases instead.
