### ISSUE TITLE
how to use this plugin create gitlab pipline?

### ISSUE THREAD

**Issue by try1995** [gocd-contrib/gitlab-oauth-authorization-plugin#166]
I finish Installation and use gitlab login, when i create git pipline(gtlab project url),  materials show error message:Modification check failed for material: URL: http://xxxxx.git, Branch: develop Affected pipelines are ai_auto_assignment.
Failed to run git clone command STDERR: Cloning into '/go-working-dir/pipelines/flyweight/ba848755-bd99-4401-a2a3-986515862a7a'... STDERR: fatal: unable to access 'http://xxxxx.git/': Could not resolve host: code.xxx.com

**Comment by chadlwilson** [comment]
Im not sure I understand your question but this plugin allows you to login with your gilab credentials. You dont need any special plugin to point to use a gitlab repository in a pipeline and it doesn't affect how the pipelines work, only your initial login.

For your pipeline configuration, the error above seema to tell you the problem - it could not resolve the hostname you have entered.

**Comment by try1995** [comment]
> Im not sure I understand your question but this plugin allows you to login with your gilab credentials. You dont need any special plugin to point to use a gitlab repository in a pipeline and it doesn't affect how the pipelines work, only your initial login.
> 
> For your pipeline configuration, the error above seema to tell you the problem - it could not resolve the hostname you have entered.

thx,i got it. i just change the host (code.xxx.com) to ip address, then solve it!
